### ISSUE TITLE
New logo for the project

### ISSUE THREAD

**Issue by camachoreina** [LA-CoNGA/WP1-Preparation#8]
During our last meeting on Nov 7th, it was decided to use the logo created by Estefania Sanchéz:
https://docs.google.com/presentation/d/1KnwV7j6UI-KwwVfzg2-ceQurR8vWMwF1rIlE8T82J1k/edit?usp=drive_web&ouid=108919011043988985345

with some modifications:
- ponerle "aspecto de cuero" al borde del círculo, un poco como en la otra propuesta.
- También hay que cambiar "LA CoNGA" por "LA-CoNGA Physics" (tal vez tocaría centrar el "Physics" una línea debajo de "LA-CoNGA")

This is urgent, since we need the logo to send the press release to the universities.

**Comment by artfisica** [comment]
Hola, Estefania ha modificado el logo:

![latest logo LA-CoNGA](http://azulpipita.com/la-conga/LA%20CoNGA_LOGO_10-11-19.jpg)

La útima decisión sería la ubicación de las letras.
Saludos

**Comment by camachoreina** [comment]
Thanks @artfisica. Let's use the first option with the letters above.
Couple of things:
- Can you please add a dash: LA-CoNGA
- How can we discriminate between the Colombian and Ecuador flag? Maybe adding something resembling the coat of arms?
- Can you provide a high quality pdf, jpeg, gif for the final one? Also one without the background.

Thanks a lot!
@camachoreina, @ocariz and @nunezluis

**Comment by artfisica** [comment]
Hi @camachoreina, all,

Thanks for the comments, yes, I will let Estefania knows.

A couple of questions:

* What do you mean as gif format?
* So, do we want it with the letter at the top of the bottom?

Please keep in mind this last set of comments I consider kind of asking "for free".

Cheers!

**Comment by camachoreina** [comment]
Hi @artfisica,

> Hi @camachoreina, all,
> 
> Thanks for the comments, yes, I will let Estefania knows.
> 
> A couple of questions:
> 
> * What do you mean as gif format?

https://whatis.techtarget.com/fileformat/GIF-Bitmap-CompuServe
I think this is the one that allows removing the background of images. But maybe this can be done in other formats (?)

> * So, do we want it with the letter at the top of the bottom?
> 
Sorry if it was not clear in the previous message, with the letters on the top.

> Please keep in mind this last set of comments I consider kind of asking "for free".
> 

I do not understand this sentence.
Thanks!

> Cheers!

**Comment by artfisica** [comment]
Sure :)
I mean to say that let's make this set of comments and requests, the last one.
Other requests relative to this and/of design that she can help us, in my opinion, must be paid.

**Comment by camachoreina** [comment]
We will keep her and your comment in mind the next time we need a graphic designer within the project. Thank Estefania from our side, for offering to make this design.

**Comment by artfisica** [comment]
Excellent!
We will come back with the adjustments as soon as possible

**Comment by artfisica** [comment]
Hi!

Estefania has made the changes, and the logo(s) is committed and ready to be used :)
https://github.com/LA-CoNGA/WP1-Preparation/tree/master/logos

Cheers,
Arturo
